version: '3.9'

services:
  linux:
    container_name: linux
    # Also possible: use ./images/Dockerfile instead
    build:
      context: ..
      dockerfile: ./Linux-On-ARM-Mac-4-Test-Case-Automation/Dockerfile
    # docker run -i
    stdin_open: true
    # docker run -t
    tty: true
    platform: linux/amd64
    environment:
      - KUBECONFIG=/kubeconfig
    # Also possible: COPY instead of bind mounting
    volumes:
      - /Users/fxie/Desktop/kubeconfig:/kubeconfig
      - /Users/fxie/Projects/openshift-tests-private/Linux-On-ARM-Mac-4-Test-Case-Automation/oc-4.12.11-linux/oc:/usr/local/bin/oc
      - /Users/fxie/Projects/openshift-tests-private:/go/src/github.com/openshift/openshift-tests-private
    command: >
      bash
